"""initial migration

Revision ID: 99da8e113e3b
Revises: 728a1e482051
Create Date: 2017-07-09 13:09:10.466365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99da8e113e3b'
down_revision = '728a1e482051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clan',
    sa.Column('parent_tag_id', sa.Integer(), nullable=False),
    sa.Column('child_tag_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['parent_tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('parent_tag_id', 'child_tag_id')
    )
    op.create_table('reply',
    sa.Column('parent_commt_id', sa.Integer(), nullable=False),
    sa.Column('child_commt_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_commt_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['parent_commt_id'], ['comments.id'], ),
    sa.PrimaryKeyConstraint('parent_commt_id', 'child_commt_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reply')
    op.drop_table('clan')
    # ### end Alembic commands ###
