"""initial migration

Revision ID: a29a92d4ae02
Revises: 702635f267be
Create Date: 2017-07-07 19:10:17.048797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a29a92d4ae02'
down_revision = '702635f267be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('demand_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'demands', ['demand_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'demand_id')
    # ### end Alembic commands ###
