"""initial migration

Revision ID: d09f8cfe4bf1
Revises: 99da8e113e3b
Create Date: 2017-07-12 23:27:01.275132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd09f8cfe4bf1'
down_revision = '99da8e113e3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('heading', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'heading')
    # ### end Alembic commands ###
